micronaut:
  application:
    name: genone_services
  security:
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:testandojdadadapokdjaopkjdopamdamdoipmaoidmaoidmaopimdaoipmwt}"'
              jws-algorithm: HS256
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 'Giovann@34097166'
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto:
netty:
  default:
    allocator:
      max-order: 3


javamail:
  authentication:
    username: 'my.username'
    password: 'my.password'

